### ISSUE TITLE
Feature Request - Smaller FOV option

### ISSUE THREAD

**Issue by geordil** [hd-zero/hdzero-goggle#356] opened 2023-09-28 21:30 UTC
Is there a way to scale down the image on the screens so the FOV is effectively smaller?

**Comment by T1LT3DBDR** [comment] 2023-09-28 21:37
The orqas pilot v2's did this and it was perfect. A 33° FOV is perfect for racing, less eye travel. Please, please we need this.

**Comment by T1LT3DBDR** [comment] 2023-10-03 14:07
It's not about scaling down vtx output, it's making the image smaller in the actual goggles, it would use less pixels. Thos video explains it l. It has nothing to do with camera FOV but everything to do with less eye travel in the goggles.

https://youtu.be/bEb1np8qTy0?si=zNiAlX-rBWuujz11

**Comment by Master92** [comment] 2023-11-12 19:50
This issue is a duplicate of #218

**Comment by HazzaHFPV** [comment] 2023-12-12 18:06
This would be a nice option indeed

**Comment by ligenxxxx** [comment] 2024-06-06 06:41
HDZero Goggle cannot support this.

**Closed by ligenxxxx** 2024-06-06 06:41 UTC
