### ISSUE TITLE
feature request -- DVR mode

### ISSUE THREAD

**Issue by JohnDGodwin** [hd-zero/hdzero-goggle#388] opened 2024-01-23 18:17 UTC
I would like to see a DVR mode in the HDZero goggles implemented that auto deletes older dvr files in the MOVIES files as the sd card gets full without having to format the sd card and lose important files such as fonts.

**Comment by evilC** [comment] 2024-01-23 18:55
Duplicate of #100

**Closed** 2024-06-06 04:17 UTC
